version: "2.4"
services:
  httpbin:
    image: kennethreitz/httpbin:latest
    ports:
     - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://httpbin/get"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 1m

  mosquitto:
    build: 
      context: .
      dockerfile: Dockerfile_eclipse-mosquitto
    ports:
     - "1883:1883"
     - "9001:9001"
  
  mqttclient:
    build:
      context: .
      dockerfile: Dockerfile_MQttClientID
    depends_on:
      - mosquitto
    
  mqttpublisher:
    build:
      context: .
      dockerfile: Dockerfile_MQttPublisherID
    depends_on:
      - mosquitto
  
  mqttclient_browser:
    image: craigderington/hivemq-client:latest
    ports:
      - "8080:8080"
    depends_on:
      - mosquitto
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 1m
    

  

